version: "3.3"
services:
  web:
    build:
      context: ../Backend/  # Directorio donde se encuentra el Dockerfile
      dockerfile: Dockerfile  # Especifica el Dockerfile a usar (opcional si se llama "Dockerfile")
    depends_on:
      - db  

  db:
    build:
      context: ../  # Directorio donde se encuentra el Dockerfile
      dockerfile: Dockerfile
    restart: on-failure

